"""
Retrieval Subsystem Constants
"""

DEFAULT_RETRIEVAL_TOP_K = 8
DEFAULT_DENSE_TOP_K = 12
DEFAULT_LEXICAL_TOP_K = 12
DEFAULT_FINAL_TOP_K = 5
DEFAULT_MIN_SCORE = 0.0

DEFAULT_DENSE_WEIGHT = 0.70
DEFAULT_LEXICAL_WEIGHT = 0.30

DEFAULT_MAX_CONTEXT_CHUNKS = 5
DEFAULT_MAX_CONTEXT_CHARACTERS = 6000

# Retrieval method identifiers
METHOD_DENSE = "dense"
METHOD_LEXICAL = "lexical"
METHOD_HYBRID = "hybrid"

# Reranker types
RERANKER_HEURISTIC = "heuristic"
RERANKER_NONE = "none"
