"""
Grounded RAG Pipeline Constants
"""

DEFAULT_FALLBACK_MESSAGE = "Information Not Found in the provided documents."

DEFAULT_MIN_EVIDENCE_SCORE = 0.35
DEFAULT_MIN_EVIDENCE_CHUNKS = 1
DEFAULT_MAX_CONTEXT_CHUNKS = 5
DEFAULT_MAX_CONTEXT_CHARACTERS = 6000

# Rejection Reasons
REASON_NO_CANDIDATES = "NO_CANDIDATES"
REASON_LOW_RELEVANCE = "LOW_RELEVANCE"
REASON_MISSING_METADATA = "MISSING_METADATA"
REASON_INCOMPATIBLE_INDEX = "INCOMPATIBLE_INDEX"
REASON_EMPTY_CONTEXT = "EMPTY_CONTEXT"
REASON_FILTERED_OUT = "FILTERED_OUT"
REASON_VALIDATION_FAILURE = "VALIDATION_FAILURE"
REASON_PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
REASON_CITATIONS_INVALID = "CITATIONS_INVALID"

# Confidence qualitative labels
CONFIDENCE_HIGH = "high"
CONFIDENCE_MEDIUM = "medium"
CONFIDENCE_LOW = "low"
